linters:
  enable-all: true
  disable:
    - scopelint # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - golint # deprecated
    - paralleltest
linters-settings:
  varnamelen:
    min-name-length: 1
  gomnd:
    ignored-functions:
      - 'strconv.*'
issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
